#!/usr/bin/env bash
# regenerate-skill-table.sh — 基于 skill frontmatter 重新生成 CLAUDE.md Skill 速查表
#
# 用法：
#   bash scripts/regenerate-skill-table.sh         # 原地重写 CLAUDE.md
#   bash scripts/regenerate-skill-table.sh --check # 只比对，不写；diff 则 exit 1
#
# 标记：
#   CLAUDE.md 必须含：
#     <!-- BEGIN SKILL-TABLE ... -->
#     ...（自动生成区域）
#     <!-- END SKILL-TABLE -->
#
# 退出码：
#   0 = 已重写 / 检查通过
#   1 = 检查模式下发现 diff，或 frontmatter 解析失败，或缺标记

set -u

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

CHECK_MODE=0
if [[ "${1:-}" == "--check" ]]; then
  CHECK_MODE=1
fi

CLAUDE="CLAUDE.md"

if ! grep -q "^<!-- BEGIN SKILL-TABLE" "$CLAUDE"; then
  echo "ERROR: $CLAUDE 缺 BEGIN SKILL-TABLE 标记" >&2
  exit 1
fi
if ! grep -q "^<!-- END SKILL-TABLE -->" "$CLAUDE"; then
  echo "ERROR: $CLAUDE 缺 END SKILL-TABLE 标记" >&2
  exit 1
fi

# 生成新块到 tempfile（按 trigger 排序）
NEW_BLOCK_FILE=$(mktemp)
trap "rm -f $NEW_BLOCK_FILE $NEW_BLOCK_FILE.tmp" EXIT

cat > "$NEW_BLOCK_FILE" <<'HEADER'
<!-- BEGIN SKILL-TABLE (auto-generated by scripts/regenerate-skill-table.sh, do not edit manually) -->

| Skill | 用途 | feature_log | version |
|---|---|---|---|
HEADER

# 收集所有 skill 行，按 trigger 排序
ROWS_TMP=$(mktemp)
for f in .claude/skills/*.md; do
  base=$(basename "$f")
  [[ "$base" == "AGENTS.md" || "$base" == "SKILL_SCHEMA.md" ]] && continue
  NAME=$(bash scripts/parse-skill-meta.sh --field name "$f")
  TRIGGER=$(bash scripts/parse-skill-meta.sh --field trigger "$f")
  DESC=$(bash scripts/parse-skill-meta.sh --field description "$f")
  FLR=$(bash scripts/parse-skill-meta.sh --field feature_log_required "$f")
  VER=$(bash scripts/parse-skill-meta.sh --field version "$f")
  if [[ -z "$NAME" || -z "$TRIGGER" ]]; then
    echo "ERROR: $f frontmatter 缺关键字段（name 或 trigger）" >&2
    rm -f "$ROWS_TMP"
    exit 1
  fi
  if [[ "$FLR" == "false" ]]; then FL_BADGE="⏭ exempt"; else FL_BADGE="✅"; fi
  echo "| \`$TRIGGER\` | $DESC | $FL_BADGE | $VER |" >> "$ROWS_TMP"
done

# 排序后追加到 NEW_BLOCK_FILE
sort "$ROWS_TMP" >> "$NEW_BLOCK_FILE"
rm -f "$ROWS_TMP"

echo "" >> "$NEW_BLOCK_FILE"
echo "<!-- END SKILL-TABLE -->" >> "$NEW_BLOCK_FILE"

# 比对 / 写入
# 用 sed/awk 提取 CLAUDE.md 中的旧块到另一 tempfile
OLD_BLOCK_FILE=$(mktemp)
awk '
  /^<!-- BEGIN SKILL-TABLE/ { capture = 1 }
  capture { print }
  /^<!-- END SKILL-TABLE -->/ && capture { exit }
' "$CLAUDE" > "$OLD_BLOCK_FILE"

if diff -q "$OLD_BLOCK_FILE" "$NEW_BLOCK_FILE" > /dev/null 2>&1; then
  rm -f "$OLD_BLOCK_FILE"
  echo "✅ SKILL-TABLE 已同步（无 diff）"
  exit 0
fi

if [[ "$CHECK_MODE" -eq 1 ]]; then
  echo "❌ SKILL-TABLE 与 frontmatter 不同步" >&2
  echo "   修复：bash scripts/regenerate-skill-table.sh && git add CLAUDE.md" >&2
  echo "" >&2
  echo "--- diff（左=CLAUDE.md 右=应该的） ---" >&2
  diff "$OLD_BLOCK_FILE" "$NEW_BLOCK_FILE" >&2
  rm -f "$OLD_BLOCK_FILE"
  exit 1
fi

rm -f "$OLD_BLOCK_FILE"

# 写入：行级处理 CLAUDE.md
OUT_TMP=$(mktemp)
awk -v new_file="$NEW_BLOCK_FILE" '
  BEGIN { in_block = 0 }
  /^<!-- BEGIN SKILL-TABLE/ {
    in_block = 1
    # 输出 new block
    while ((getline line < new_file) > 0) print line
    close(new_file)
    next
  }
  /^<!-- END SKILL-TABLE -->/ && in_block {
    in_block = 0
    next
  }
  !in_block { print }
' "$CLAUDE" > "$OUT_TMP"

mv "$OUT_TMP" "$CLAUDE"
echo "✅ 已重写 $CLAUDE 中 SKILL-TABLE 段（基于 frontmatter）"
